runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /_queue/async.*
  script: main.furious_app
  login: admin

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"
